### ISSUE TITLE
Link to manuscript points nowhere

### ISSUE THREAD

**Issue by jvfe** [NuriaQueralt/ngly1-graph#7]
Hi! First of all, amazing project, just a heads up:

The link to the manuscript, in your README, currently points nowhere:

> [Queralt-Rosinach *et al.* 2019](): Manuscript describing the project.

I believe it's meant to be pointing to https://academic.oup.com/database/article/doi/10.1093/database/baaa015/5818923

Cheers,
João.

**Comment by NuriaQueralt** [comment]
Bom dia!

Thank you very much for your nice words about the project! You are
completely right, the link was missing. I have just fixed it. Again, thank
you so much for letting me know. Yes, the publication is the one you wrote
down.

With best wishes,
Núria
